# Generated by Django 4.0 on 2021-12-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0002_alter_car_avg_rating_alter_car_rates_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
