# Generated by Django 4.0 on 2021-12-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0003_alter_car_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='rates_number',
            field=models.SmallIntegerField(null=True),
        ),
    ]
