# Generated by Django 4.0 on 2021-12-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0004_alter_car_avg_rating_alter_car_rates_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
