# Generated by Django 4.0 on 2021-12-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0005_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='car_id',
            field=models.SmallIntegerField(null=True),
        ),
    ]
