# Generated by Django 4.0 on 2021-12-28 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0007_alter_rate_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='car_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='carsapp.car'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
