# Generated by Django 4.0 on 2021-12-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0011_alter_rate_car_id_alter_rate_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='car_id',
            field=models.SmallIntegerField(),
        ),
    ]
