# Generated by Django 4.0 on 2021-12-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0014_alter_car_rates_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rates_number',
            field=models.CharField(max_length=44),
        ),
    ]
