# Generated by Django 4.0 on 2021-12-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0016_ratenew_delete_rate_alter_car_rates_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratenew',
            name='car_id',
        ),
    ]
