# Generated by Django 4.0 on 2021-12-28 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0017_remove_ratenew_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratenew',
            name='car_rate_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_id', to='carsapp.car'),
        ),
    ]
