# Generated by Django 4.0 on 2021-12-28 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0018_alter_ratenew_car_rate_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, null=True)),
                ('car_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsapp.car')),
            ],
        ),
        migrations.DeleteModel(
            name='RateNew',
        ),
    ]
