# Generated by Django 4.0 on 2021-12-28 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0019_newrate_delete_ratenew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrate',
            name='car_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_name', to='carsapp.car'),
        ),
    ]
